## Prediction of possibility of working based on years after graduation, field of study, number of connections (in LinkedIn), work specialization, school

#### Learning Algorithm: Gaussian Naive Bayes

In [1]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')
data.head()


educations-end_date  educations-field_of_study  num-connections  \
0                    1                          8                0   
1                    2                          8                3   
2                   27                          5               36   
3                   20                          0                0   
4                   12                          8                5   

   industry-specialization  educations-school-name_asnumeric  \
0                        4                                10   
1                        5                                10   
2                        3                                 9   
3                        0                                 4   
4                        4                                 9   

   positions_is_current  
0                     0  
1                     1  
2                     0  
3                     1  
4                     0

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[['educations-field_of_study', 'num-connections', 'industry-specialization', 'educations-school-name_asnumeric']], data[['positions_is_current']], test_size=0.3, random_state=427)

y_train = y_train.values.flatten() # Just some trivial data formatting..
y_test = y_test.values.flatten()

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train, y_train)

y_score = gnb.predict(X_test)
y_score

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [3]:
gnb.predict_proba(X_test)

array([[ 0.77141232,  0.22858768],
       [ 0.61640105,  0.38359895],
       [ 0.66112353,  0.33887647],
       ..., 
       [ 0.6085215 ,  0.3914785 ],
       [ 0.66887363,  0.33112637],
       [ 0.828162  ,  0.171838  ]])

In [4]:
from sklearn import datasets, metrics
classification = ["True", "False"]
print(metrics.classification_report(y_test, y_score, target_names=classification, digits=4))
pred = gnb.predict(X_test)
print(metrics.confusion_matrix(pred, y_test))

             precision    recall  f1-score   support

       True     0.7944    1.0000    0.8854       479
      False     0.0000    0.0000    0.0000       124

avg / total     0.6310    0.7944    0.7033       603



/Users/zenitharnejo/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


#### Learning Algorithm: Support Vector Machines

In [6]:
import numpy as np
from sklearn import svm
import math
import pandas as pd
from sklearn import datasets, metrics

filedata = 'philippine_file.csv'
data = pd.read_csv(filedata)
data.columns.values

n = len(data)
num_train = int(0.70*n)

data = data.sample(frac=1).reset_index(drop=True)
classes = data["positions_is_current"]

y = data["positions_is_current"][:num_train]
y_test = data["positions_is_current"][num_train:]
del data["positions_is_current"]
X = data[:num_train]
X_test = data[num_train:]

model = svm.SVC(kernel='linear',C=15).fit(X,y)
#model = svm.SVC(kernel='poly',C=1, degree=2, probability=True).fit(X,y)
#model = svm.SVC(kernel='rbf',C=100, gamma=4).fit(X,y)

model.fit(X, y)
pred = model.predict(X_test)
print(metrics.confusion_matrix(pred, y_test))
print(model.score(X_test,y_test))
trial = data.head(1)
print(model.predict(trial))
print("test input(class): ", classes[1])
print("test input(data): ")
data.head(1)
len(data)

[[470 133]
 [  0   0]]
0.77943615257
[0]
test input(class):  0
test input(data): 


2007

#### Learning Algorithm: Artificial Neural Network

In [7]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')

In [8]:
x = data.drop('positions_is_current',axis=1) #axis=1 tells the translator that a column will be dropped, 0 if row
y = data['positions_is_current']
y

0       0
1       1
2       0
3       1
4       0
5       1
6       0
7       0
8       0
9       1
10      0
11      1
12      0
13      1
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      1
22      1
23      0
24      0
25      0
26      0
27      1
28      0
29      0
       ..
1977    0
1978    0
1979    1
1980    0
1981    1
1982    1
1983    0
1984    0
1985    1
1986    0
1987    1
1988    0
1989    1
1990    0
1991    0
1992    0
1993    0
1994    0
1995    1
1996    1
1997    0
1998    0
1999    1
2000    0
2001    0
2002    0
2003    0
2004    0
2005    1
2006    1
Name: positions_is_current, Length: 2007, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y)

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()#StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_test

array([[ 0.07407407,  1.        ,  0.        ,  1.        ,  1.        ],
       [ 0.31481481,  0.        ,  0.002     ,  0.        ,  0.2       ],
       [ 0.16666667,  1.        ,  0.02      ,  0.875     ,  1.        ],
       ..., 
       [ 0.09259259,  1.        ,  0.194     ,  1.        ,  0.2       ],
       [ 0.2037037 ,  1.        ,  0.046     ,  0.375     ,  1.        ],
       [ 0.2962963 ,  1.        ,  0.018     ,  1.        ,  1.        ]])

In [10]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(5),max_iter=5000,learning_rate_init=0.1,activation='tanh')
mlp.fit(x_train,y_train)

predictions = mlp.predict(x_test)
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [11]:
from sklearn.metrics import classification_report,confusion_matrix

print (confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[389   0]
 [113   0]]
             precision    recall  f1-score   support

          0       0.77      1.00      0.87       389
          1       0.00      0.00      0.00       113

avg / total       0.60      0.77      0.68       502



/Users/zenitharnejo/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Prediction of work specialization based on field of study, school, year after graduation, educations-end_date

#### Learning Algorithm: Multinomial Naive Bayes

In [12]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')
data.head()

educations-end_date  educations-field_of_study  num-connections  \
0                    1                          8                0   
1                    2                          8                3   
2                   27                          5               36   
3                   20                          0                0   
4                   12                          8                5   

   industry-specialization  educations-school-name_asnumeric  \
0                        4                                10   
1                        5                                10   
2                        3                                 9   
3                        0                                 4   
4                        4                                 9   

   positions_is_current  
0                     0  
1                     1  
2                     0  
3                     1  
4                     0

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data[['educations-field_of_study', 'educations-school-name_asnumeric', 'educations-end_date']], data[['industry-specialization']], test_size=0.3, random_state=427)

y_train = y_train.values.flatten() # Just some trivial data formatting..
y_test = y_test.values.flatten()
X_train = X_train.values.flatten() # Just some trivial data formatting..
X_test = X_test.values.flatten()

print("X_train ", X_train.shape)
print("y_train ", y_train.shape)



X_train  (4212,)
y_train  (1404,)


In [14]:
# Importing packages necessary for building the model
from sklearn.feature_extraction.text import CountVectorizer #converts the content to vector
from sklearn.naive_bayes import MultinomialNB 
from sklearn.pipeline import Pipeline #vectorize then multinomialNB; as in a pipelined steps

text_clf = Pipeline([('vect_tfid', CountVectorizer()),
                     ('clf', MultinomialNB())]) #alpha automatically signals laplace correction, include alpha as parameter

##text_clf = text_clf.fit(X_train, y_train) #fit the model to the training set


In [15]:
#text_clf is the generated model
# y_predicted = text_clf.predict(X_test) #get predicted classes
# y_predicted

#### Learning Algorithm: Support Vector Machines (SVM)

In [16]:
import pandas as pd
from sklearn import preprocessing

filedata = 'philippine_file.csv'
data = pd.read_csv(filedata)

del data["num-connections"]
del data["positions_is_current"]
del data["educations-end_date"]

n = len(data)
num_train = int(0.60*n)

data = data.sample(frac=1).reset_index(drop=True)
classes = data["industry-specialization"]

y = data["industry-specialization"][:num_train]
y_test = data["industry-specialization"][num_train:]
del data["industry-specialization"]

x = data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
data = pd.DataFrame(x_scaled)

X = data[:num_train]
X_test = data[num_train:]

model = svm.SVC(kernel='linear',C=100).fit(X,y)
#model = svm.SVC(kernel='poly',C=200, degree=2, probability=True).fit(X,y)
#model = svm.SVC(kernel='rbf',C=100, gamma=5, ).fit(X,y)

pred = model.predict(X_test)
print(metrics.confusion_matrix(pred, y_test))
print(model.score(X_test,y_test))
trial = data.head(1)
print(model.predict(trial))
print("test input(class): ", classes[1])

[[  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [ 49  16  24  97  12  17   3  20  75]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [ 68  20  19  86  26   8  44  61 158]]


/Users/zenitharnejo/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


0.317559153176
[8]
test input(class):  8


#### Learning Algorithm: Artificial Neural Network

In [17]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')

In [18]:
del data["num-connections"]
del data["positions_is_current"]

x = data.drop('industry-specialization',axis=1) #axis=1 tells the translator that a column will be dropped, 0 if row
y = data['industry-specialization']
y

0       4
1       5
2       3
3       0
4       4
5       4
6       3
7       3
8       3
9       7
10      1
11      3
12      4
13      7
14      6
15      3
16      8
17      8
18      0
19      0
20      3
21      3
22      7
23      3
24      2
25      3
26      3
27      7
28      4
29      4
       ..
1977    3
1978    3
1979    7
1980    0
1981    0
1982    3
1983    3
1984    3
1985    6
1986    8
1987    7
1988    7
1989    4
1990    6
1991    8
1992    8
1993    8
1994    1
1995    7
1996    4
1997    1
1998    8
1999    8
2000    0
2001    0
2002    3
2003    3
2004    0
2005    8
2006    3
Name: industry-specialization, Length: 2007, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y)

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()#StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_test

array([[ 0.28846154,  0.375     ,  0.3       ],
       [ 0.19230769,  1.        ,  0.9       ],
       [ 0.25      ,  1.        ,  0.9       ],
       ..., 
       [ 0.32692308,  1.        ,  0.4       ],
       [ 0.19230769,  1.        ,  0.9       ],
       [ 0.11538462,  0.5       ,  0.9       ]])

In [20]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(5),max_iter=5000,learning_rate_init=0.1,activation='tanh')
mlp.fit(x_train,y_train)

predictions = mlp.predict(x_test)
print(predictions)

[3 8 8 8 8 8 8 8 3 8 8 3 3 3 3 8 8 8 0 8 3 8 8 3 3 8 8 8 8 0 3 3 8 3 3 8 8
 8 8 3 3 8 8 3 8 8 8 8 8 8 8 8 3 0 8 8 8 8 8 3 3 8 8 3 8 8 8 0 8 8 8 8 8 8
 8 8 8 8 8 3 8 3 0 8 0 3 8 3 0 8 0 3 3 0 8 8 3 8 8 8 3 8 8 8 3 8 8 8 8 8 3
 8 8 3 8 3 3 8 8 8 3 8 8 8 8 3 8 8 8 3 3 3 3 3 8 8 8 3 8 3 8 0 8 3 3 8 8 8
 8 8 8 8 3 8 3 8 3 8 3 3 8 8 8 8 8 0 3 8 8 8 8 8 8 8 3 3 8 3 8 8 8 3 0 8 8
 0 8 3 8 3 0 8 8 8 8 3 3 8 8 8 3 8 8 8 8 3 8 3 8 8 3 3 3 8 8 8 8 8 8 0 8 8
 8 3 8 8 8 3 8 3 8 8 3 3 8 3 3 3 8 8 3 8 8 8 8 3 3 8 8 8 8 3 8 8 8 0 3 8 8
 8 8 8 8 8 0 8 8 8 3 3 8 8 8 8 8 3 0 8 0 8 3 8 8 8 3 8 8 8 8 3 3 3 8 3 8 8
 8 8 0 3 8 8 8 8 8 3 8 8 8 8 3 3 8 3 8 8 8 3 3 8 3 3 8 8 8 8 8 8 3 3 0 0 8
 8 8 0 8 8 8 8 8 0 3 3 8 8 8 8 8 8 0 8 8 8 8 0 8 3 8 8 8 8 3 3 8 8 8 8 0 3
 8 3 8 8 3 8 8 8 0 3 3 8 0 8 8 8 3 8 8 3 8 3 3 8 3 8 8 8 8 8 8 0 3 8 8 8 3
 3 8 3 3 8 3 3 8 8 8 8 8 8 8 8 8 8 8 8 3 3 3 3 8 8 3 8 8 8 8 3 8 8 8 8 8 8
 8 8 8 3 8 8 8 8 3 3 3 3 8 8 8 8 8 3 8 3 8 8 8 3 3 3 8 8 8 3 8 8 3 3 8 8 0
 8 0 8 0 3 8 3 3 0 8 8 8 

In [21]:
from sklearn.metrics import classification_report,confusion_matrix

print (confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 20   0   0   5   0   0   0   0  34]
 [  1   0   0   7   0   0   0   0  15]
 [  0   0   0   4   0   0   0   0  17]
 [  1   0   0  52   0   0   0   0  52]
 [  2   0   0   7   0   0   0   0  20]
 [  0   0   0  10   0   0   0   0   7]
 [  0   0   0   7   0   0   0   0  30]
 [  7   0   0  15   0   0   0   0  46]
 [  4   0   0  35   0   0   0   0 104]]
             precision    recall  f1-score   support

          0       0.57      0.34      0.43        59
          1       0.00      0.00      0.00        23
          2       0.00      0.00      0.00        21
          3       0.37      0.50      0.42       105
          4       0.00      0.00      0.00        29
          5       0.00      0.00      0.00        17
          6       0.00      0.00      0.00        37
          7       0.00      0.00      0.00        68
          8       0.32      0.73      0.44       143

avg / total       0.23      0.35      0.26       502



/Users/zenitharnejo/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
