## Prediction of possibility of working based on years after graduation, field of study, number of connections (in LinkedIn), work specialization, school

#### Learning Algorithm: Gaussian Naive Bayes

In [1]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')
data.head()


educations-end_date  educations-field_of_study  num-connections  \
0                    1                         16                0   
1                    2                         16                3   
2                   27                          6               36   
3                   20                          0                0   
4                   12                         16                5   

   industry-specialization  educations-school-name_asnumeric  \
0                        5                                25   
1                        6                                25   
2                        4                                24   
3                        0                                14   
4                        5                                24   

   positions_is_current  
0                     0  
1                     1  
2                     0  
3                     1  
4                     0

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[['educations-field_of_study', 'num-connections', 'industry-specialization', 'educations-school-name_asnumeric']], data[['positions_is_current']], test_size=0.3, random_state=427)

y_train = y_train.values.flatten() # Just some trivial data formatting..
y_test = y_test.values.flatten()

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train, y_train)

y_score = gnb.predict(X_test)
y_score

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [15]:
gnb.predict_proba(X_test)

array([[ 0.74958041,  0.25041959],
       [ 0.63715682,  0.36284318],
       [ 0.66054519,  0.33945481],
       ..., 
       [ 0.63202801,  0.36797199],
       [ 0.64228451,  0.35771549],
       [ 0.83868444,  0.16131556]])

In [16]:
from sklearn import datasets, metrics
classification = ["True", "False"]
print(metrics.classification_report(y_test, y_score, target_names=classification, digits=4))

             precision    recall  f1-score   support

       True     0.7944    1.0000    0.8854       479
      False     0.0000    0.0000    0.0000       124

avg / total     0.6310    0.7944    0.7033       603



/Users/zenitharnejo/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [17]:
pred = gnb.predict(X_test)
print(metrics.confusion_matrix(pred, y_test))

[[479 124]
 [  0   0]]


#### Learning Algorithm: Support Vector Machines

In [76]:
import numpy as np
from sklearn import svm
import math
import pandas as pd
from sklearn import datasets, metrics

filedata = 'philippine_file.csv'
data = pd.read_csv(filedata)
data.columns.values

n = len(data)
num_train = int(0.70*n)

data = data.sample(frac=1).reset_index(drop=True)
classes = data["positions_is_current"]

y = data["positions_is_current"][:num_train]
y_test = data["positions_is_current"][num_train:]
del data["positions_is_current"]
X = data[:num_train]
X_test = data[num_train:]

model = svm.SVC(kernel='linear',C=15).fit(X,y)
#model = svm.SVC(kernel='poly',C=1, degree=2, probability=True).fit(X,y)
#model = svm.SVC(kernel='rbf',C=100, gamma=4).fit(X,y)

model.fit(X, y)
pred = model.predict(X_test)
print(metrics.confusion_matrix(pred, y_test))
print(model.score(X_test,y_test))
trial = data.head(1)
print(model.predict(trial))
print("test input(class): ", classes[1])
print("test input(data): ")
data.head(1)
len(data)

[[450 153]
 [  0   0]]
0.746268656716
[0]
test input(class):  0
test input(data): 


2007

#### Learning Algorithm: Artificial Neural Network

In [78]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')

In [80]:
x = data.drop('positions_is_current',axis=1) #axis=1 tells the translator that a column will be dropped, 0 if row
y = data['positions_is_current']
y

0       0
1       1
2       0
3       1
4       0
5       1
6       0
7       0
8       0
9       1
10      0
11      1
12      0
13      1
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      1
22      1
23      0
24      0
25      0
26      0
27      1
28      0
29      0
       ..
1977    0
1978    0
1979    1
1980    0
1981    1
1982    1
1983    0
1984    0
1985    1
1986    0
1987    1
1988    0
1989    1
1990    0
1991    0
1992    0
1993    0
1994    0
1995    1
1996    1
1997    0
1998    0
1999    1
2000    0
2001    0
2002    0
2003    0
2004    0
2005    1
2006    1
Name: positions_is_current, Length: 2007, dtype: int64

In [81]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y)

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()#StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_test

array([[ 0.16666667,  0.5       ,  1.        ,  1.        ,  1.        ],
       [ 0.1875    ,  0.25      ,  0.006     ,  0.25      ,  0.96      ],
       [ 0.35416667,  1.        ,  0.002     ,  0.25      ,  1.        ],
       ..., 
       [ 0.10416667,  1.        ,  0.24      ,  0.375     ,  0.12      ],
       [ 0.3125    ,  1.        ,  0.008     ,  1.        ,  1.        ],
       [ 0.22916667,  1.        ,  0.218     ,  0.1875    ,  0.48      ]])

In [82]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(5),max_iter=5000,learning_rate_init=0.1,activation='tanh')
mlp.fit(x_train,y_train)

predictions = mlp.predict(x_test)
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [83]:
from sklearn.metrics import classification_report,confusion_matrix

print (confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[399   0]
 [103   0]]
             precision    recall  f1-score   support

          0       0.79      1.00      0.89       399
          1       0.00      0.00      0.00       103

avg / total       0.63      0.79      0.70       502



/Users/zenitharnejo/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Prediction of work specialization based on field of study, school, year after graduation, educations-end_date

#### Learning Algorithm: Multinomial Naive Bayes

In [38]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')
data.head()

educations-end_date  educations-field_of_study  num-connections  \
0                    1                         16                0   
1                    2                         16                3   
2                   27                          6               36   
3                   20                          0                0   
4                   12                         16                5   

   industry-specialization  educations-school-name_asnumeric  \
0                        5                                25   
1                        6                                25   
2                        4                                24   
3                        0                                14   
4                        5                                24   

   positions_is_current  
0                     0  
1                     1  
2                     0  
3                     1  
4                     0

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data[['educations-field_of_study', 'educations-school-name_asnumeric', 'educations-end_date']], data[['industry-specialization']], test_size=0.3, random_state=427)

y_train = y_train.values.flatten() # Just some trivial data formatting..
y_test = y_test.values.flatten()
X_train = X_train.values.flatten() # Just some trivial data formatting..
X_test = X_test.values.flatten()

print("X_train ", X_train.shape)
print("y_train ", y_train.shape)



X_train  (4212,)
y_train  (1404,)


In [45]:
# Importing packages necessary for building the model
from sklearn.feature_extraction.text import CountVectorizer #converts the content to vector
from sklearn.naive_bayes import MultinomialNB 
from sklearn.pipeline import Pipeline #vectorize then multinomialNB; as in a pipelined steps

text_clf = Pipeline([('vect_tfid', CountVectorizer()),
                     ('clf', MultinomialNB())]) #alpha automatically signals laplace correction, include alpha as parameter

text_clf = text_clf.fit(X_train, y_train) #fit the model to the training set


In [ ]:
#text_clf is the generated model
y_predicted = text_clf.predict(X_test) #get predicted classes
y_predicted

#### Learning Algorithm: Support Vector Machines (SVM)

In [64]:
import pandas as pd
from sklearn import preprocessing

filedata = 'philippine_file.csv'
data = pd.read_csv(filedata)

del data["num-connections"]
del data["positions_is_current"]
del data["educations-end_date"]

n = len(data)
num_train = int(0.60*n)

data = data.sample(frac=1).reset_index(drop=True)
classes = data["industry-specialization"]

y = data["industry-specialization"][:num_train]
y_test = data["industry-specialization"][num_train:]
del data["industry-specialization"]

x = data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
data = pd.DataFrame(x_scaled)

X = data[:num_train]
X_test = data[num_train:]

model = svm.SVC(kernel='linear',C=100).fit(X,y)
#model = svm.SVC(kernel='poly',C=200, degree=2, probability=True).fit(X,y)
#model = svm.SVC(kernel='rbf',C=100, gamma=5, ).fit(X,y)

pred = model.predict(X_test)
print(metrics.confusion_matrix(pred, y_test))
print(model.score(X_test,y_test))
trial = data.head(1)
print(model.predict(trial))
print("test input(class): ", classes[1])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 45   9  14   9 117  13  11  17  18  11  12   4   0   3   4  14  68]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 

/Users/zenitharnejo/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


#### Learning Algorithm: Artificial Neural Network

In [79]:
import pandas as pd

data = pd.read_csv('philippine_file.csv')

In [67]:
del data["num-connections"]
del data["positions_is_current"]

x = data.drop('industry-specialization',axis=1) #axis=1 tells the translator that a column will be dropped, 0 if row
y = data['industry-specialization']
y

0        5
1        6
2        4
3        0
4        5
5        5
6        4
7        4
8        4
9        1
10      13
11       4
12       5
13      10
14       7
15       4
16      16
17      16
18       0
19       0
20       4
21       4
22       8
23       4
24       9
25       4
26       4
27       8
28       5
29       5
        ..
1977     4
1978     4
1979    10
1980     0
1981     0
1982     4
1983     4
1984     4
1985     7
1986    16
1987     1
1988     1
1989     5
1990     7
1991    15
1992    16
1993    16
1994     2
1995    10
1996     5
1997     2
1998    14
1999    16
2000     0
2001     0
2002     4
2003     4
2004     0
2005    14
2006     4
Name: industry-specialization, Length: 2007, dtype: int64

In [68]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y)

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()#StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_test

In [72]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(5),max_iter=5000,learning_rate_init=0.1,activation='tanh')
mlp.fit(x_train,y_train)

predictions = mlp.predict(x_test)
print(predictions)

MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=5, learning_rate='constant',
       learning_rate_init=0.1, max_iter=5000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [74]:
from sklearn.metrics import classification_report,confusion_matrix

print (confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 0  0  0  1 30  0  0  0  0  0  0  0  0  0  0  0 34]
 [ 0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0 15]
 [ 0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0 73  0  0  0  0  0  0  0  0  0  0  0 44]
 [ 0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0 13]
 [ 0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  7]
 [ 0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0 13]
 [ 0  0  0  1  7  0  0  0  0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  5]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  6]
 [ 0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  0  0  0  0  0  0  0  0  0  0  0 10]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0 17]
 [ 0  0  0  0 34  0  0  0  0  0  0  0  0  0  0  0 83]]
